"""add table post_liker_table

Revision ID: 080b3e9c8af0
Revises: f58e07670c5f
Create Date: 2021-06-21 22:12:57.345735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080b3e9c8af0'
down_revision = 'f58e07670c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_liker_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('post_pid', sa.String(length=100), nullable=True),
    sa.Column('liker_pid', sa.String(length=100), nullable=True),
    sa.Column('is_unliked', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['liker_pid'], ['user.public_id'], ),
    sa.ForeignKeyConstraint(['post_pid'], ['post.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_liker_table')
    # ### end Alembic commands ###
