"""empty message

Revision ID: 1ec996437291
Revises: 0406c9db66b2
Create Date: 2021-05-23 17:37:29.009380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec996437291'
down_revision = '0406c9db66b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('user_executive_id', sa.String(), nullable=False))
    op.drop_constraint('business_user_exec_id_fkey', 'business', type_='foreignkey')
    op.create_foreign_key(None, 'business', 'user', ['user_executive_id'], ['public_id'])
    op.drop_column('business', 'user_exec_id')
    op.add_column('post', sa.Column('business_pinboard_id', sa.String(), nullable=True))
    op.add_column('post', sa.Column('circle_confiner_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'post', 'business', ['business_pinboard_id'], ['public_id'])
    op.create_foreign_key(None, 'post', 'circle', ['circle_confiner_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'circle_confiner_id')
    op.drop_column('post', 'business_pinboard_id')
    op.add_column('business', sa.Column('user_exec_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.create_foreign_key('business_user_exec_id_fkey', 'business', 'user', ['user_exec_id'], ['public_id'])
    op.drop_column('business', 'user_executive_id')
    # ### end Alembic commands ###
