"""empty message

Revision ID: 22686a97cf15
Revises: 
Create Date: 2021-03-22 11:05:14.045188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22686a97cf15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('specie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('breed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('specie_parent_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['specie_parent_id'], ['specie.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('business',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('user_exec_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_exec_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=400), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('user_creator_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_creator_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('business_operation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.Time(), nullable=True),
    sa.Column('end_at', sa.Time(), nullable=True),
    sa.Column('business_prop_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['business_prop_id'], ['business.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('business_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('business_prop_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['business_prop_id'], ['business.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('user_owner_id', sa.String(), nullable=False),
    sa.Column('specie_group_id', sa.String(), nullable=False),
    sa.Column('breed_subgroup_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['breed_subgroup_id'], ['breed.public_id'], ),
    sa.ForeignKeyConstraint(['specie_group_id'], ['specie.public_id'], ),
    sa.ForeignKeyConstraint(['user_owner_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('business_type')
    op.drop_table('business_operation')
    op.drop_table('post')
    op.drop_table('business')
    op.drop_table('breed')
    op.drop_table('user')
    op.drop_table('specie')
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
