"""added post_subject_table to cater tagged pets in posts

Revision ID: 29e91c38ac82
Revises: 4e088cc6281f
Create Date: 2021-06-04 09:20:48.584348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e91c38ac82'
down_revision = '4e088cc6281f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_subject_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('post_pid', sa.String(length=100), nullable=True),
    sa.Column('subject_pid', sa.String(length=100), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_pid'], ['post.public_id'], ),
    sa.ForeignKeyConstraint(['subject_pid'], ['pet.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_subject_table')
    # ### end Alembic commands ###
