"""empty message

Revision ID: 2d602c55b0df
Revises: 22686a97cf15
Create Date: 2021-03-23 08:46:12.233674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d602c55b0df'
down_revision = '22686a97cf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_type', sa.Column('registered_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_type', 'registered_on')
    # ### end Alembic commands ###
