"""change pet sex db type to integer

Revision ID: 3332bf2b14a3
Revises: 8c10ad2e9307
Create Date: 2020-12-28 19:21:53.881815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3332bf2b14a3'
down_revision = '8c10ad2e9307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('user_owner_id', sa.String(), nullable=False),
    sa.Column('specie_group_id', sa.String(), nullable=False),
    sa.Column('breed_subgroup_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['breed_subgroup_id'], ['breed.public_id'], ),
    sa.ForeignKeyConstraint(['specie_group_id'], ['specie.public_id'], ),
    sa.ForeignKeyConstraint(['user_owner_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
