"""empty message

Revision ID: 360dde3f09c5
Revises: f50ba200c9b8
Create Date: 2021-06-03 12:58:46.655168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360dde3f09c5'
down_revision = 'f50ba200c9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'is_private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
