"""empty message

Revision ID: 3d0155611ed8
Revises: 2d602c55b0df
Create Date: 2021-03-23 08:48:18.268736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0155611ed8'
down_revision = '2d602c55b0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('type_prop_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'business', 'business_type', ['type_prop_id'], ['public_id'])
    op.drop_constraint('business_type_business_prop_id_fkey', 'business_type', type_='foreignkey')
    op.drop_column('business_type', 'business_prop_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_type', sa.Column('business_prop_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('business_type_business_prop_id_fkey', 'business_type', 'business', ['business_prop_id'], ['public_id'])
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_column('business', 'type_prop_id')
    # ### end Alembic commands ###
