"""change pet privacy type to int

Revision ID: 4e088cc6281f
Revises: 360dde3f09c5
Create Date: 2021-06-03 13:00:01.987481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e088cc6281f'
down_revision = '360dde3f09c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('is_private', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'is_private')
    # ### end Alembic commands ###
