"""empty message

Revision ID: 71d69b274c4e
Revises: 5abdb8bddf38
Create Date: 2021-05-12 16:41:23.052191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d69b274c4e'
down_revision = '5abdb8bddf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle_membership_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('circle_pid', sa.String(length=100), nullable=True),
    sa.Column('member_pid', sa.String(length=100), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_pid'], ['circle.public_id'], ),
    sa.ForeignKeyConstraint(['member_pid'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circle_membership_table')
    # ### end Alembic commands ###
