"""business table added

Revision ID: 7e8f6a8ff160
Revises: 3332bf2b14a3
Create Date: 2021-01-04 09:51:18.784480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8f6a8ff160'
down_revision = '3332bf2b14a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('_type', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('user_exec_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_exec_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business')
    # ### end Alembic commands ###
