"""empty message

Revision ID: 88338cc5e4cd
Revises: 3d0155611ed8
Create Date: 2021-03-23 13:45:35.392280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88338cc5e4cd'
down_revision = '3d0155611ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_type_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('business_id', sa.String(length=100), nullable=True),
    sa.Column('type_id', sa.String(length=100), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.public_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['business_type.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.drop_constraint('business_type_prop_id_fkey', 'business', type_='foreignkey')
    op.drop_column('business', 'type_prop_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('type_prop_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('business_type_prop_id_fkey', 'business', 'business_type', ['type_prop_id'], ['public_id'])
    op.drop_table('business_type_table')
    # ### end Alembic commands ###
