"""empty message

Revision ID: a9cdabe71553
Revises: e3a2ea945e50
Create Date: 2021-04-13 15:01:05.845005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cdabe71553'
down_revision = 'e3a2ea945e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('circle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('user_admin_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_admin_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('circle_type_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('circle_pid', sa.String(length=100), nullable=True),
    sa.Column('type_pid', sa.String(length=100), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circle_pid'], ['circle.public_id'], ),
    sa.ForeignKeyConstraint(['type_pid'], ['circle_type.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circle_type_table')
    op.drop_table('circle')
    op.drop_table('circle_type')
    # ### end Alembic commands ###
