"""empty message

Revision ID: eaa4648c3658
Revises: 88338cc5e4cd
Create Date: 2021-03-23 13:48:57.713864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa4648c3658'
down_revision = '88338cc5e4cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_type_table', sa.Column('business_pid', sa.String(length=100), nullable=True))
    op.add_column('business_type_table', sa.Column('type_pid', sa.String(length=100), nullable=True))
    op.drop_constraint('business_type_table_business_id_fkey', 'business_type_table', type_='foreignkey')
    op.drop_constraint('business_type_table_type_id_fkey', 'business_type_table', type_='foreignkey')
    op.create_foreign_key(None, 'business_type_table', 'business', ['business_pid'], ['public_id'])
    op.create_foreign_key(None, 'business_type_table', 'business_type', ['type_pid'], ['public_id'])
    op.drop_column('business_type_table', 'business_id')
    op.drop_column('business_type_table', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_type_table', sa.Column('type_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('business_type_table', sa.Column('business_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'business_type_table', type_='foreignkey')
    op.drop_constraint(None, 'business_type_table', type_='foreignkey')
    op.create_foreign_key('business_type_table_type_id_fkey', 'business_type_table', 'business_type', ['type_id'], ['public_id'])
    op.create_foreign_key('business_type_table_business_id_fkey', 'business_type_table', 'business', ['business_id'], ['public_id'])
    op.drop_column('business_type_table', 'type_pid')
    op.drop_column('business_type_table', 'business_pid')
    # ### end Alembic commands ###
