"""added post_parent_id in post model to accomodate comments in posts

Revision ID: eb325d2e7b63
Revises: 6958dc8da4b7
Create Date: 2021-06-19 15:29:12.273643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb325d2e7b63'
down_revision = '6958dc8da4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_parent_id', sa.String(), nullable=True))
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    op.create_foreign_key(None, 'post', 'post', ['post_parent_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    op.drop_column('post', 'post_parent_id')
    # ### end Alembic commands ###
