"""new model: comment

Revision ID: f58e07670c5f
Revises: eb325d2e7b63
Create Date: 2021-06-21 11:55:18.552389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58e07670c5f'
down_revision = 'eb325d2e7b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=400), nullable=False),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('user_creator_id', sa.String(), nullable=False),
    sa.Column('post_parent_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['post_parent_id'], ['post.public_id'], ),
    sa.ForeignKeyConstraint(['user_creator_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.drop_constraint('post_post_parent_id_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'post_parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_parent_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_post_parent_id_fkey', 'post', 'post', ['post_parent_id'], ['public_id'])
    op.drop_table('comment')
    # ### end Alembic commands ###
